FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

ARG APP_UID=1000
RUN mkdir -p /app/keys && chown -R ${APP_UID}:${APP_UID} /app

USER ${APP_UID}

EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["ContactManager/ContactManager.csproj", "ContactManager/"]
RUN dotnet restore "ContactManager/ContactManager.csproj"
COPY . .
WORKDIR "/src/ContactManager"
RUN dotnet build "./ContactManager.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./ContactManager.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

VOLUME ["/app/keys"]

ENTRYPOINT ["dotnet", "ContactManager.dll"]
